apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: gitops-clusters
        requeueAfterSeconds: 30
  template:
    metadata:
      name: wordpress-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: wordpress
        targetRevision: 16.0.4
      destination:
        namespace: wordpress
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-clusters
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
    cluster: local-cluster
  placementRef:
    name: gitops-clusters
    namespace: openshift-gitops
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement